table customer
	lineageTag: 998ee791-e3e7-4995-bb4c-311f69e794e6

	column customer_key
		dataType: string
		lineageTag: d4f9ad00-a061-4b1a-8912-62f1cdfbdad1
		summarizeBy: none
		sourceColumn: customer_key

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: ec7c726c-5d04-4584-9faf-383378a05bb0
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_name
		dataType: string
		lineageTag: b24c337f-8a8f-4e88-96df-c79d0fb4b418
		summarizeBy: none
		sourceColumn: customer_name

		annotation SummarizationSetBy = Automatic

	column customer_country
		dataType: string
		lineageTag: be69684b-f9e4-499f-a17b-a22f4576d0a3
		summarizeBy: none
		sourceColumn: customer_country

		annotation SummarizationSetBy = Automatic

	column 'customer_region '
		dataType: string
		lineageTag: 159a2485-0379-4b47-a0a3-2439ed790b05
		summarizeBy: none
		sourceColumn: "customer_region "

		annotation SummarizationSetBy = Automatic

	column dimension_1
		dataType: string
		lineageTag: 8a76adb3-7872-4861-bb05-a9709dc3165f
		summarizeBy: none
		sourceColumn: dimension_1

		annotation SummarizationSetBy = Automatic

	partition customer = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\SujithaaR\Downloads\customer.csv"),[Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_key", type text}, {"customer_id", Int64.Type}, {"customer_name", type text}, {"customer_country", type text}, {"customer_region ", type text}, {"dimension_1", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

