table Product
	lineageTag: e08df0e9-3357-4438-b9ea-6421a2a6db49

	column product_key
		dataType: string
		lineageTag: e17a26ef-1e08-427b-9590-7ee998a7c88a
		summarizeBy: none
		sourceColumn: product_key

		annotation SummarizationSetBy = Automatic

	column product_level_1
		dataType: string
		lineageTag: 933781be-613c-4a79-8683-3a85d2034c61
		summarizeBy: none
		sourceColumn: product_level_1

		annotation SummarizationSetBy = Automatic

	column product_level_2
		dataType: string
		lineageTag: 66e96f48-dacc-4dc4-9f0d-39f019e028ca
		summarizeBy: none
		sourceColumn: product_level_2

		annotation SummarizationSetBy = Automatic

	column revenue_type
		dataType: int64
		formatString: 0
		lineageTag: 05cb14a6-9fc7-4b48-899d-2b61e9dacded
		summarizeBy: none
		sourceColumn: revenue_type

		annotation SummarizationSetBy = Automatic

	partition Product = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\SujithaaR\Downloads\Product.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"product_key", type text}, {"product_level_1", type text}, {"product_level_2", type text}, {"revenue_type", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

