table snowball_output
	lineageTag: d5216803-8d21-4eee-84ab-25b0c1ba906f

	measure churn = DIVIDE(SUM(snowball_output[customer_churn]),SUM(snowball_output[bop_arr]),0)*100
		lineageTag: 8ee9c782-2600-4ec2-ac04-f8dd5d7dc97e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column snowball_key
		dataType: string
		lineageTag: c7a7ba26-2ab6-4f51-8319-da6c9678a39d
		summarizeBy: none
		sourceColumn: snowball_key

		annotation SummarizationSetBy = Automatic

	column customer_key
		dataType: string
		lineageTag: 957c47fb-b5f2-4ad8-88a1-acd9bdcb435c
		summarizeBy: none
		sourceColumn: customer_key

		annotation SummarizationSetBy = Automatic

	column product_key
		dataType: string
		lineageTag: 00609f69-61a6-4d41-92b0-cb7d1d6733b1
		summarizeBy: none
		sourceColumn: product_key

		annotation SummarizationSetBy = Automatic

	column month_roll
		dataType: dateTime
		formatString: dd-mm-yyyy
		lineageTag: 5d7b5a36-b390-4320-9d82-b6c6c31dd90f
		summarizeBy: none
		sourceColumn: month_roll

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column period_type
		dataType: string
		lineageTag: 3beb0c59-de3b-4d83-9ac4-6a7e503974ec
		summarizeBy: none
		sourceColumn: period_type

		annotation SummarizationSetBy = Automatic

	column bop_arr
		dataType: double
		lineageTag: 7f90226b-aafa-46be-9d1b-3d462e41b91d
		summarizeBy: sum
		sourceColumn: bop_arr

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column customer_churn
		dataType: double
		lineageTag: 0d1a3941-dce5-4407-bdea-abdb798f55ad
		summarizeBy: sum
		sourceColumn: customer_churn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column product_churn
		dataType: double
		lineageTag: 84e9d480-c83b-47b4-80a2-6aa990c7097a
		summarizeBy: sum
		sourceColumn: product_churn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column downsell
		dataType: double
		lineageTag: c3e883dc-af27-4724-9b9b-4347dfc808b5
		summarizeBy: sum
		sourceColumn: downsell

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column grr
		dataType: double
		lineageTag: 8ed3f6be-00ea-426f-9e01-047ec6689c24
		summarizeBy: sum
		sourceColumn: grr

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column upsell
		dataType: double
		lineageTag: c7fb0e89-6af6-4566-a8eb-39e09f2ee4de
		summarizeBy: sum
		sourceColumn: upsell

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cross_sell
		dataType: int64
		formatString: 0
		lineageTag: a4653a6d-26e7-46f1-b5ce-00da6df4d14d
		summarizeBy: sum
		sourceColumn: cross_sell

		annotation SummarizationSetBy = Automatic

	column nrr
		dataType: double
		lineageTag: c067efec-6e7f-4460-890f-4da63e82ce56
		summarizeBy: sum
		sourceColumn: nrr

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column new_customer
		dataType: double
		lineageTag: dbfe34dc-cd81-40b0-b564-664d7b2e2508
		summarizeBy: sum
		sourceColumn: new_customer

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column eop_arr
		dataType: double
		lineageTag: 594cf59d-ed61-420a-9e2e-29e1b5660a67
		summarizeBy: sum
		sourceColumn: eop_arr

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition snowball_output = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\SujithaaR\Downloads\snowball_output.csv"),[Delimiter=",", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"snowball_key", type text}, {"customer_key", type text}, {"product_key", type text}, {"month_roll", type date}, {"period_type", type text}, {"bop_arr", type number}, {"customer_churn", type number}, {"product_churn", type number}, {"downsell", type number}, {"grr", type number}, {"upsell", type number}, {"cross_sell", Int64.Type}, {"nrr", type number}, {"new_customer", type number}, {"eop_arr", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

